/**
 * Per-route metadata for server-side HTML injection.
 *
 * ⚠️  DO NOT edit this file directly.
 * All SEO metadata (title, description, h1, bodySnippet) now lives in:
 *   shared/seo-routes.ts
 *
 * Edit that file to update any page's title or meta description.
 * Both the server (this file) and the client SEO component read from
 * the same source, so changes propagate everywhere automatically.
 */

import { seoRoutes, type RouteSeoDef } from '@shared/seo-routes';

// Re-export the interface under the legacy name so existing consumers compile.
export type RouteMeta = RouteSeoDef;

/** Legacy map export — kept for any code that still does routeMetaMap[path] */
export const routeMetaMap: Record<string, RouteMeta> = seoRoutes;

/**
 * Look up SEO metadata for a given pathname.
 * Falls back to the homepage entry if no exact match is found.
 */
export function getRouteMeta(pathname: string): RouteMeta {
  const normalized =
    pathname !== '/' && pathname.endsWith('/')
      ? pathname.slice(0, -1)
      : pathname;

  return (
    seoRoutes[normalized] ||
    seoRoutes[pathname] || {
      title: 'Hero Handyman Pro | Handyman & Home Repair in St. Louis & Metro East',
      description:
        'Hero Handyman Pro provides trusted handyman & home repair services in St. Louis & Metro East. Deck repair, carpentry, drywall, and more — licensed, insured, and easy to schedule.',
      h1: 'Hero Handyman Pro — Trusted Local Handyman Services',
      bodySnippet:
        'Hero Handyman Pro provides trusted handyman and home repair services across St. Louis, MO and Metro East Illinois. Call 800-741-6056 for a free estimate.',
      canonicalUrl: 'https://www.herohandymanpro.com',
    }
  );
}

/**
 * Inject page-specific metadata into the HTML template string.
 * Replaces the generic <title> and <meta name="description"> tags,
 * and appends a hidden static content block inside <body> for crawlers.
 */
export function injectRouteMeta(html: string, pathname: string): string {
  const meta = getRouteMeta(pathname);

  // Replace <title>
  let result = html.replace(
    /<title>[^<]*<\/title>/,
    `<title>${escapeHtml(meta.title)}</title>`
  );

  // Replace <meta name="description">
  result = result.replace(
    /<meta\s+name="description"\s+content="[^"]*"\s*\/?>/,
    `<meta name="description" content="${escapeHtml(meta.description)}" />`
  );

  // Inject noindex if requested
  if (meta.noindex) {
    result = result.replace(
      /<meta\s+name="robots"\s+content="[^"]*"\s*\/?>/,
      `<meta name="robots" content="noindex, follow" />`
    );
  }

  // Inject canonical URL if present
  if (meta.canonicalUrl) {
    const canonicalTag = `<link rel="canonical" href="${escapeHtml(meta.canonicalUrl)}" />`;
    if (!result.includes('rel="canonical"')) {
      result = result.replace('</head>', `${canonicalTag}\n</head>`);
    } else {
      result = result.replace(
        /<link\s+rel="canonical"\s+href="[^"]*"\s*\/?>/,
        canonicalTag
      );
    }
  }

  // Inject static content block before </body> for crawlers
  const staticBlock = `
<!-- static-seo-content: visible to crawlers before JS executes -->
<div id="seo-static-content" style="position:absolute;left:-9999px;top:-9999px;width:1px;height:1px;overflow:hidden;" aria-hidden="true">
  <h1>${escapeHtml(meta.h1)}</h1>
  <p>${escapeHtml(meta.bodySnippet)}</p>
  <p>Hero Handyman Pro | Phone: 800-741-6056 | herohandymanpro.com</p>
</div>`;

  result = result.replace('</body>', staticBlock + '\n</body>');
  return result;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
